apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: t05iz9btx-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/t05iz9btx-java-quarkus-gitops